name: Deploy to Cloudflare Pages

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v4.1.0
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v4.2.0
        with:
          node-version: 23
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install 

      - name: Initialize environment variables
        run: echo "PUBLIC_SUPABASE_URL=${{ secrets.PUBLIC_SUPABASE_URL }}" >> $GITHUB_ENV && echo "PUBLIC_SUPABASE_ANON_KEY=${{ secrets.PUBLIC_SUPABASE_ANON_KEY }}" >> $GITHUB_ENV && echo "PUBLIC_SITE_URL=${{ secrets.PUBLIC_SITE_URL }}" >> $GITHUB_ENV

      - name: Build
        run: pnpm build

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy .svelte-kit/cloudflare/ --project-name=pokeromcodex
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}